Added a new requester config to add custom system headers
postmanlabs/postman-runtime pull request #1128
Opened 2021-03-04 13:40 UTC by mayank3012jain

new config: `systemHeaders` 
These headers cannot be disabled or overridden and are added with `system` flag set to true.

Code changes:
Added a new function `addCustomSystemHeaders` which is called from `getRequestOptions()`. This function adds all the headers to `request.headers` object and updates any header if it is already present.

2021-03-08 13:03 UTC, codenirvana requested changes

2021-03-08 13:03 UTC, codenirvana commented on test/integration/requester-spec/systemHeaders.test.js
> +                                'foo': 'Bar'
```suggestion
                                'foo': true
```

2021-03-08 13:03 UTC, codenirvana commented on test/integration/requester-spec/systemHeaders.test.js
> +    describe('with request sent from script', function () {
```suggestion
    describe('with pm.sendRequest', function () {
```

2021-03-08 13:03 UTC, codenirvana commented on test/integration/requester-spec/systemHeaders.test.js
> +            expect(testrun.assertion.getCall(0).args[1][0]).to.include({
just check passed: true

2021-03-08 17:18 UTC, mayank3012jain commented on test/integration/requester-spec/systemHeaders.test.js
> +            expect(headers[0].system).to.equal(true);
Equality does not work between two instances of PostmanHeader.
This will also break every time a new property is added to the header.

2021-03-15 05:44 UTC, codenirvana approved these changes

2021-03-15 05:44 UTC, merged